# Rule Validation Schema (Production)
$schema: "http://json-schema.org/draft-07/schema#"
type: object
required:
  - rule_id
  - name
  - priority
  - domain
  - description
  - trigger
  - action
properties:
  rule_id:
    type: string
    pattern: "^[A-Z]{3,5}-[A-Z]{3,5}-[0-9]{3}$"
    description: "Format: [DOMAIN]-[CATEGORY]-[ID] (e.g., CORP-CONT-001)"
  name:
    type: string
  priority:
    type: string
    enum: ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
  domain:
    type: string
    enum: ["CORE", "CORPORATE", "LITIGATION", "IP_LAW", "PRIVACY"]
  description:
    type: string
  trigger:
    type: object
    required:
      - context
    properties:
      context:
        type: string
        enum: ["contract_analysis", "legal_research", "drafting", "compliance", "prediction"]
      action_type:
        type: string
      document_type:
        type: string
  condition:
    type: object
    description: "Logic conditions for rule matching"
  action:
    type: object
    required:
      - type
      - message
    properties:
      type:
        type: string
        enum: ["ALLOW", "BLOCK", "WARN", "ESCALATE", "MASK"]
      message:
        type: string
      parameters:
        type: object
  on_fail:
    type: string
    enum: ["retry", "escalate", "abort"]
